# 🎉 semantic-alias/celebration.yaml
# 用途：涵蓋節日慶典、生日、祝賀、派對、禮物等喜慶場景，適用於社群互動、祝賀訊息與節日應景貼文。
- alias: 生日
  emojis: 🎂 🎉 🎁 🎈
- alias: 派對
  emojis: 🥳 🎉 🎊 🍾
- alias: 慶祝
  emojis: 🎊 🎉 🎈
- alias: 祝賀
  emojis: 🎉 🥂 👏
- alias: 禮物
  emojis: 🎁 🎀 🛍️
- alias: 驚喜
  emojis: 🎁 😲 🤩
- alias: 結婚
  emojis: 💒 👰 🤵 💍
- alias: 求婚
  emojis: 💍 💌 ❤️
- alias: 情人節
  emojis: 💘 💝 ❤️
- alias: 耶誕節
  emojis: 🎄 🎅 🎁
- alias: 跨年
  emojis: 🎆 🕛 🥂
- alias: 新年
  emojis: 🧨 🧧 🐲 🎊
- alias: 春節
  emojis: 🧧 🧨 🏮
- alias: 中秋
  emojis: 🥮 🌕 🏮
- alias: 萬聖節
  emojis: 🎃 👻 🕸️
- alias: 感恩節
  emojis: 🦃 🍂 🥧
- alias: 聖誕老公公
  emojis: 🎅 🎁
- alias: 放假
  emojis: 🌴 🏖️ 🧘
- alias: 長假
  emojis: 📆 🏝️ 🧳
- alias: 回家
  emojis: 🏠 🚗 🎒
- alias: 吃大餐
  emojis: 🍽️ 🍗 🍰
- alias: 發紅包
  emojis: 🧧 💰
- alias: 拜年
  emojis: 🙇 🧧 🎍
