# 🖥️ Console 輸出語境（log、debug提示）
- alias: 初始化
  emojis: ♻️
- alias: 輸入
  emojis: ⌨️
- alias: 輸出
  emojis: 📤
- alias: 監聽
  emojis: 👂
- alias: 偵測
  emojis: 🕵️
- alias: 停用
  emojis: 🚫
- alias: 啟用
  emojis: 🔓
- alias: 模擬
  emojis: 🎮
- alias: 模糊
  emojis: 🌫️
- alias: 除名
  emojis: 🗑️
- alias: 跳過
  emojis: ⏭️
- alias: 排除
  emojis: 🚷
- alias: 捕捉
  emojis: 📸
- alias: 重導
  emojis: 🔁
