# ✅ 註解語境（開發文件、架構圖）
- alias: 範例
  emojis: 🧾
- alias: 備援
  emojis: 🧯
- alias: 快取
  emojis: 🧂
- alias: 暫存
  emojis: 🗃️
- alias: 描述
  emojis: 🖋️
- alias: 關聯
  emojis: 🔗
- alias: 限制
  emojis: ⛓️
- alias: 流程圖
  emojis: 🗺️
- alias: 層級
  emojis: 🧅
- alias: 通道
  emojis: 🛤️
