# 😊 semantic-alias/emotion.yaml
# 用途：涵蓋日常情緒表達，適用於聊天、社群互動、貼文留言、日記等場合。
- alias: 開心
  emojis: 😀 😄 😁 😊 😸
- alias: 高興
  emojis: 😄 😃 😆 🎉
- alias: 滿足
  emojis: 😊 😌 😋
- alias: 感動
  emojis: 🥹 😢 😭 ❤️
- alias: 難過
  emojis: 😢 😞 😔 😿
- alias: 哭
  emojis: 😭 😢 😿
- alias: 傷心
  emojis: 💔 😞 😢
- alias: 生氣
  emojis: 😡 😠 😤 👿
- alias: 火大
  emojis: 🔥 😤 😡
- alias: 無奈
  emojis: 😑 🙄 😓
- alias: 累
  emojis: 😴 🥱 😪 😩
- alias: 睏
  emojis: 🥱 😪 🛌
- alias: 緊張
  emojis: 😰 😨 😱 😬
- alias: 驚訝
  emojis: 😲 😯 😮 😳
- alias: 害羞
  emojis: 😊 🙈 😳
- alias: 有趣
  emojis: 😆 😹 😄 🎉
- alias: 好笑
  emojis: 😂 😹 🤣
- alias: 嚇到
  emojis: 😱 😨 👻
- alias: 放鬆
  emojis: 😌 🧘 ☕
- alias: 冷靜
  emojis: 🧘 😐 🫥
- alias: 煩躁
  emojis: 😤 😣 😫
- alias: 無聊
  emojis: 🥱 😐 💤
- alias: 痛苦
  emojis: 😖 😩 😫
- alias: 疑惑
  emojis: 🤔 ❓ 🧐
- alias: 喜愛
  emojis: ❤️ 😍 🥰 💖
- alias: 心動
  emojis: 💓 💘 ❤️‍🔥
- alias: 愛心
  emojis: ❤️ 💗 💕 💞
- alias: 黑心
  emojis: 🖤 😈
