# 💬 semantic-alias/reaction.yaml
# 用途：涵蓋即時社交互動中的情緒與反應，例如回應貼文、聊天對話、直播互動等。常用於表達主觀感受、支持、吐槽與幽默。
- alias: 讚
  emojis: 👍 💯 🫶
- alias: 加油
  emojis: 💪 👊 🙌
- alias: 鼓掌
  emojis: 👏 🙌
- alias: 贊成
  emojis: ✅ 🤝 👍
- alias: 反對
  emojis: ❌ 👎 🙅
- alias: 喜歡
  emojis: ❤️ 🥰 😍
- alias: 討厭
  emojis: 🤢 👎 🚫
- alias: 哈哈
  emojis: 😂 🤣 😹
- alias: 哭哭
  emojis: 😢 😭 😿
- alias: 吐槽
  emojis: 🙄 😒 😤
- alias: 無言
  emojis: 😑 🙃 🤐
- alias: 嚇到
  emojis: 😱 😨 🫣
- alias: 驚訝
  emojis: 😲 😯 😳
- alias: 疑惑
  emojis: 🤔 🧐 ❓
- alias: 拍手
  emojis: 👏 🙌
- alias: 高能
  emojis: ⚡🔥 💥
- alias: 安慰
  emojis: 🤗 🫂 💖
- alias: 推薦
  emojis: 👍 🌟 💡
- alias: 不推
  emojis: 👎 ❌ 🚫
- alias: 留言
  emojis: 💬 🗯️
- alias: 回覆
  emojis: 📩 🔁
- alias: 轉發
  emojis: 🔁 🔄
