# 🧑‍🤝‍🧑 semantic-alias/relationship.yaml
# 用途：涵蓋人際關係與互動情境，包括家人、愛情、友情、社交圈等語意，適合用於聊天、社群貼文或紀錄日常互動。
- alias: 家人
  emojis: 👨‍👩‍👧‍👦 🏠 ❤️
- alias: 爸爸
  emojis: 👨 👨‍🦱 👔
- alias: 媽媽
  emojis: 👩 👩‍🦰 🧺
- alias: 小孩
  emojis: 🧒 👶 🧸
- alias: 兄弟
  emojis: 👦 🤼
- alias: 姐妹
  emojis: 👧 👭
- alias: 親戚
  emojis: 👵 👴 🧓
- alias: 朋友
  emojis: 🧑‍🤝‍🧑 🤝 👫
- alias: 同學
  emojis: 🎒 📚
- alias: 同事
  emojis: 💼 🧑‍💻
- alias: 老闆
  emojis: 🧑‍💼 👨‍💼
- alias: 愛情
  emojis: ❤️ 💕 💑
- alias: 戀愛
  emojis: 🥰 💘 💏
- alias: 交往
  emojis: 💑 🤝
- alias: 告白
  emojis: 💌 💓
- alias: 結婚
  emojis: 💍 👰 🤵 💒
- alias: 離婚
  emojis: 💔 🔪
- alias: 單身
  emojis: 🙋 😎
- alias: 社交
  emojis: 🗣️ 👥
- alias: 聚會
  emojis: 🎉 🍻
- alias: 拜訪
  emojis: 🚪 👋
- alias: 擁抱
  emojis: 🤗 🫂
- alias: 親吻
  emojis: 😘 💋
- alias: 想念
  emojis: 😢 💭 ❤️
- alias: 分離
  emojis: 🥀 😔
